name: CI
on:
  - push
  - pull_request
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: fmt
      # XXX validate fails with strange errors:
      # > Error: Missing required argument
      # > The argument "username" is required, but was not set.
      #- name: Terraform Init
        #uses: hashicorp/terraform-github-actions@master
        #with:
          #tf_actions_subcommand: init
          #tf_actions_version: latest
      #- name: 'Terraform Validate'
        #uses: hashicorp/terraform-github-actions@master
        #with:
          #tf_actions_subcommand: validate
          #tf_actions_version: latest
